"""empty message

Revision ID: 07323e352fa6
Revises: afd10367e451
Create Date: 2024-07-25 12:21:24.696434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07323e352fa6'
down_revision = 'afd10367e451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###
