"""empty message

Revision ID: c18e1d7d1f8b
Revises: b4ce251354e8
Create Date: 2024-07-26 12:13:45.752708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18e1d7d1f8b'
down_revision = 'b4ce251354e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=True),
    sa.Column('planet_fk', sa.Integer(), nullable=True),
    sa.Column('people_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_fk'], ['people.people_id'], ),
    sa.ForeignKeyConstraint(['planet_fk'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_fk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
